# Day 3

In [2]:
import numpy as np

data = open(
    '/content/drive/MyDrive/Colab Notebooks/AOC/2021/day3.txt',
    'r')
mat = []

for _ in data.readlines():
    blst = list(_.rstrip())
    mat.append(list(map(int, blst)))

mat = np.array(mat, dtype = np.int8)
mat

array([[0, 0, 0, ..., 0, 1, 0],
       [0, 1, 1, ..., 0, 1, 1],
       [1, 0, 0, ..., 1, 0, 1],
       ...,
       [1, 1, 1, ..., 1, 0, 0],
       [0, 0, 0, ..., 0, 0, 1],
       [0, 0, 0, ..., 0, 0, 1]], dtype=int8)

## Part 1

In [3]:
def findPowerConsumption(mat: np.ndarray) -> int:
    counts = np.apply_along_axis(np.bincount, 0, mat)
    print(counts)
    bits = mat.shape[1]
    gamma = 0
    epsilon = 0
    for i, (num_zero, num_ones) in enumerate(zip(counts[0], counts[1])):
        if num_ones > num_zero: # 1 is most common bit
            gamma += 2**(bits - (i+1))
        else:
            # 1 is least common bit
            epsilon += 2**(bits - (i+1))

    return gamma*epsilon


In [4]:
findPowerConsumption(mat)

[[481 519 493 499 504 505 496 508 517 502 515 490]
 [519 481 507 501 496 495 504 492 483 498 485 510]]


3549854

## Part 2

In [5]:
def findRating(mat: np.ndarray, is_oxy=True) -> int:
    """
    Helper method to compute oxygen generator and CO2 scrubber rating
    """
    bits = mat.shape[1]
    rating = 0
    for i in range(bits):
        if mat.shape[0] == 1: # 1 number left
            break
        else:
            # Find counts of 0, 1 in each column
            col = mat[:, i]
            # print(col)
            counts = np.bincount(col)
            if counts[1] > counts[0]: # 1 is most common bit
                indexes = [k for k, b in enumerate(col) if b] if is_oxy \
                else [k for k, b in enumerate(col) if not b]
            elif counts[0] > counts [1]: # 0 is most common bit
                indexes = [k for k, b in enumerate(col) if not b] if is_oxy \
                else [k for k, b in enumerate(col) if b]
            else: # 1 and 0 equally common
                indexes = [k for k, b in enumerate(col) if b] if is_oxy \
                else [k for k, b in enumerate(col) if not b]

            mat = mat[indexes, :]
            # print("Numbers left: ", mat)

    for idx, bit in enumerate(mat[0]):
        if bit: rating += 2**(bits - (idx + 1))

    return rating


def findLifeSupportRating(mat: np.ndarray) -> int:
    O2Rating = findRating(mat)
    CO2Rating = findRating(mat, False)

    return O2Rating*CO2Rating

In [7]:
findLifeSupportRating(mat)

3765399