# Day 15

In [ ]:
import numpy as np
data = open(
    '/content/drive/MyDrive/Colab Notebooks/AOC/2021/day15.txt',
    'r')

mat = []
for line in data.readlines():
    arr = list(line.rstrip())
    mat.append(list(map(int, arr)))

mat = np.array(mat, dtype = np.int8)

## Part 1

In [ ]:
import heapq

def findLowestRiskLevel(input: np.ndarray) -> int:
    """
    Idea: Apply Dijkstra's algorithm to find shortest path,
    with risk levels as distances
    """
    m, n = input.shape
    start, end = (0,0), (m-1,n-1)
    # Initialize distance(risk) table
    D = np.matrix(np.ones((m, n)) * np.inf)
    # Set of visited nodes (node cloud)
    visited = set()
    D[start] = 0

    def getNeighbours(point, visited):
        neighbours = []
        i, j = point[0], point[1]
        for nei in [(i-1, j), (i+1, j), (i, j-1), (i, j+1)]:
            if nei[0] < 0 or nei[0] >= m or nei[1] < 0 or nei[1] >= n:
                continue
            elif nei not in visited:
                visited.add(nei)
                neighbours.append(nei)
        return neighbours

    # Initialize heap as priority queue
    Q = []
    Q.append((0, start)) # (priority(risk), node)
    while len(Q) > 0:
        # Get closest unvisited node to node cloud
        v = heapq.heappop(Q)[1]
        # Update distances to neighbouring nodes
        for node in getNeighbours(v, visited):
            dist = D[v] + input[node]
            if dist < D[node]:
                D[node] = dist
                heapq.heappush(Q, (dist, node))

    print(D)
    return D[end]

In [ ]:
findLowestRiskLevel(mat)

[[  0.   1.   6. ... 274. 282. 281.]
 [  1.   9.   9. ... 273. 277. 279.]
 [ 10.  17.  11. ... 272. 273. 277.]
 ...
 [314. 314. 305. ... 404. 407. 408.]
 [320. 311. 306. ... 400. 407. 416.]
 [316. 315. 310. ... 405. 414. 415.]]


415.0

## Part 2

In [ ]:
def constructFullMap(input: np.ndarray) -> np.ndarray:
    rows, cols = input.shape
    fullMap = np.zeros((rows*5, cols*5))
    # Construct column-wise expansion of initial map
    for k in range(5):
        fullMap[:rows, k*cols:(k+1)*cols] = input + k
    # Construct row-wise expansion
    for k in range(1,5):
        fullMap[k*rows:(k+1)*rows, :] = fullMap[(k-1)*rows:k*rows, :] + 1
    # To wrap resulting values from a - b,
    # use formula (x - a) % (b - a + 1) + a
    return (fullMap - 1) % 9 + 1

In [ ]:
findLowestRiskLevel(constructFullMap(mat))

[[0.000e+00 1.000e+00 6.000e+00 ... 1.735e+03 1.738e+03 1.744e+03]
 [1.000e+00 9.000e+00 9.000e+00 ... 1.738e+03 1.746e+03 1.750e+03]
 [1.000e+01 1.700e+01 1.100e+01 ... 1.743e+03 1.748e+03 1.756e+03]
 ...
 [1.777e+03 1.780e+03 1.776e+03 ... 2.839e+03 2.841e+03 2.850e+03]
 [1.781e+03 1.789e+03 1.781e+03 ... 2.848e+03 2.847e+03 2.855e+03]
 [1.786e+03 1.794e+03 1.785e+03 ... 2.852e+03 2.855e+03 2.864e+03]]


2864.0